import useWaitForHydration from "@/hooks/useWaitForHydration";
import { Button, Calendar, DatePicker, Form, Input } from "antd";
import { Dayjs } from "dayjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { IncomingMessage } from "http";
import { NextApiRequestQuery } from "next/dist/server/api-utils";
import { useTranslation } from "next-i18next";

export default function Home() {
  const { t } = useTranslation();
  const [dates, setDates] = useState<any>([]);
  const [currentDate, setCurrentDate] = useState<Dayjs>();
  const [form] = Form.useForm();
  const router = useRouter();

  const handleDateSelect = (date: Dayjs) => {
    if (!date) return;
    setCurrentDate(date);
    const datesTmp = [...dates];
    if (
      datesTmp.find(
        (d: Dayjs) => d.format("YYYY-MM-DD") === date.format("YYYY-MM-DD")
      )
    ) {
      const index = datesTmp.findIndex(
        (d: Dayjs) => d.format("YYYY-MM-DD") === date.format("YYYY-MM-DD")
      );
      datesTmp.splice(index, 1);
      setDates(datesTmp);
      return;
    }
    setDates([...datesTmp, date]);
  };

  const handleSubmit = (value: any) => {
    const body = {
      ...value,
      date: dates.map((d: Dayjs) => d.format("YYYY-MM-DD"))
    };
    window.open(
      `mailto:caissy.alex@gmail.com?subject=Test Guest Email&body=${JSON.stringify(
        body
      )}`,
      "_blank",
      "scrollbars=yes,resizable=yes,width=10,height=10"
    );
  };

  const [isHydrated, loader] = useWaitForHydration();
  if (!isHydrated) return loader;

  return (
    <>
      <Head>
        <title>Bébélala Guest Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <div className="logo">
          <h1>Guest</h1>
          <Image src="/logo.png" width={100} height={100} alt="logo" />
          <h1>Sheet</h1>
        </div>
        <Form layout="vertical" onFinish={handleSubmit} form={form}>
          <Form.Item name="lastName" label="Last Name">
            <Input />
          </Form.Item>
          <Form.Item name="firstName" label="First Name">
            <Input />
          </Form.Item>
          <Form.Item name="pronouns" label="Pronouns">
            <Input />
          </Form.Item>
          <Form.Item name="email" label="Email">
            <Input />
          </Form.Item>
          <Form.Item name="phone" label="Cellphone">
            <Input />
          </Form.Item>
          <Form.Item name="social" label="Instagram Handle">
            <Input prefix="@" />
          </Form.Item>
          <Form.Item name="date" label="Date">
            <Calendar
              value={currentDate}
              fullscreen={false}
              onPanelChange={(e) => setCurrentDate(undefined)}
              onSelect={(date) => handleDateSelect(date)}
              dateFullCellRender={(date: Dayjs) => (
                <div
                  className={`date-container ${
                    dates.find(
                      (d: Dayjs) =>
                        d.format("YYYY-MM-DD") === date.format("YYYY-MM-DD")
                    )
                      ? "selected"
                      : ""
                  }`}
                >
                  <span>{date.get("date")}</span>
                </div>
              )}
            />
          </Form.Item>
          <Button htmlType="submit">Submit</Button>
        </Form>
        <Link href="/" locale={router.locale === "en" ? "fr" : "en"}>
          {router.locale}
        </Link>
      </main>
    </>
  );
}

interface ServerSideProps extends IncomingMessage {
  locale: string;
  query?: NextApiRequestQuery;
}

export async function getStaticProps({ locale }: ServerSideProps) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"]))
      // Will be passed to the page component as props
    }
  };
}
